/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'commission' : IDL.Nat,
  'sizes' : IDL.Vec(IDL.Text),
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'colors' : IDL.Vec(IDL.Text),
  'price' : IDL.Nat,
});
export const ProductId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'commission' : IDL.Nat,
  'sizes' : IDL.Vec(IDL.Text),
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'colors' : IDL.Vec(IDL.Text),
  'price' : IDL.Nat,
});
export const SessionToken = IDL.Text;
export const LoginResult = IDL.Variant({
  'ok' : SessionToken,
  'err' : IDL.Text,
});
export const PaymentMethod = IDL.Variant({
  'COD' : IDL.Null,
  'UPI' : IDL.Null,
});
export const OrderInput = IDL.Record({
  'customerName' : IDL.Text,
  'paymentMethod' : PaymentMethod,
  'customerPhone' : IDL.Text,
  'productColor' : IDL.Text,
  'productId' : ProductId,
  'productName' : IDL.Text,
  'productSize' : IDL.Text,
  'customerAddress' : IDL.Text,
  'razorpayOrderId' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Nat,
  'customerEmail' : IDL.Opt(IDL.Text),
  'productPrice' : IDL.Nat,
});
export const OrderId = IDL.Nat;
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'placed' : IDL.Null,
  'delivered' : IDL.Null,
  'processing' : IDL.Null,
});
export const CashbackStatus = IDL.Variant({
  'pending' : IDL.Null,
  'given' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'razorpayPaymentId' : IDL.Opt(IDL.Text),
  'customerName' : IDL.Text,
  'deliveryTimestamp' : IDL.Opt(Timestamp),
  'paymentStatus' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'customerPhone' : IDL.Text,
  'orderStatus' : OrderStatus,
  'cashbackTimestamp' : IDL.Opt(Timestamp),
  'createdAt' : Timestamp,
  'productColor' : IDL.Text,
  'productId' : ProductId,
  'productName' : IDL.Text,
  'productSize' : IDL.Text,
  'customerAddress' : IDL.Text,
  'razorpayOrderId' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Nat,
  'customerEmail' : IDL.Opt(IDL.Text),
  'cashbackStatus' : CashbackStatus,
  'productPrice' : IDL.Nat,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([ProductInput], [Product], []),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
  'adminLogout' : IDL.Func([IDL.Text], [], []),
  'createOrder' : IDL.Func([OrderInput], [IDL.Nat], []),
  'createRazorpayOrder' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Text], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getTotalOrders' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalProducts' : IDL.Func([], [IDL.Nat], ['query']),
  'listOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'markCashbackGiven' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], []),
  'markDelivered' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateOrderPaymentStatus' : IDL.Func(
      [IDL.Nat, PaymentStatus, IDL.Opt(IDL.Text)],
      [IDL.Opt(Order)],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [IDL.Opt(Order)], []),
  'updateProduct' : IDL.Func([IDL.Nat, ProductInput], [IDL.Opt(Product)], []),
  'validateAdminSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'verifyRazorpayPayment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'commission' : IDL.Nat,
    'sizes' : IDL.Vec(IDL.Text),
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'colors' : IDL.Vec(IDL.Text),
    'price' : IDL.Nat,
  });
  const ProductId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'commission' : IDL.Nat,
    'sizes' : IDL.Vec(IDL.Text),
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'colors' : IDL.Vec(IDL.Text),
    'price' : IDL.Nat,
  });
  const SessionToken = IDL.Text;
  const LoginResult = IDL.Variant({ 'ok' : SessionToken, 'err' : IDL.Text });
  const PaymentMethod = IDL.Variant({ 'COD' : IDL.Null, 'UPI' : IDL.Null });
  const OrderInput = IDL.Record({
    'customerName' : IDL.Text,
    'paymentMethod' : PaymentMethod,
    'customerPhone' : IDL.Text,
    'productColor' : IDL.Text,
    'productId' : ProductId,
    'productName' : IDL.Text,
    'productSize' : IDL.Text,
    'customerAddress' : IDL.Text,
    'razorpayOrderId' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Nat,
    'customerEmail' : IDL.Opt(IDL.Text),
    'productPrice' : IDL.Nat,
  });
  const OrderId = IDL.Nat;
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'placed' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
  });
  const CashbackStatus = IDL.Variant({
    'pending' : IDL.Null,
    'given' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'razorpayPaymentId' : IDL.Opt(IDL.Text),
    'customerName' : IDL.Text,
    'deliveryTimestamp' : IDL.Opt(Timestamp),
    'paymentStatus' : PaymentStatus,
    'paymentMethod' : PaymentMethod,
    'customerPhone' : IDL.Text,
    'orderStatus' : OrderStatus,
    'cashbackTimestamp' : IDL.Opt(Timestamp),
    'createdAt' : Timestamp,
    'productColor' : IDL.Text,
    'productId' : ProductId,
    'productName' : IDL.Text,
    'productSize' : IDL.Text,
    'customerAddress' : IDL.Text,
    'razorpayOrderId' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Nat,
    'customerEmail' : IDL.Opt(IDL.Text),
    'cashbackStatus' : CashbackStatus,
    'productPrice' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func([ProductInput], [Product], []),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
    'adminLogout' : IDL.Func([IDL.Text], [], []),
    'createOrder' : IDL.Func([OrderInput], [IDL.Nat], []),
    'createRazorpayOrder' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Text], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getTotalOrders' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalProducts' : IDL.Func([], [IDL.Nat], ['query']),
    'listOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'markCashbackGiven' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], []),
    'markDelivered' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateOrderPaymentStatus' : IDL.Func(
        [IDL.Nat, PaymentStatus, IDL.Opt(IDL.Text)],
        [IDL.Opt(Order)],
        [],
      ),
    'updateOrderStatus' : IDL.Func(
        [IDL.Nat, OrderStatus],
        [IDL.Opt(Order)],
        [],
      ),
    'updateProduct' : IDL.Func([IDL.Nat, ProductInput], [IDL.Opt(Product)], []),
    'validateAdminSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'verifyRazorpayPayment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };