/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CashbackStatus = { 'pending' : null } |
  { 'given' : null };
export type LoginResult = { 'ok' : SessionToken } |
  { 'err' : string };
export interface Order {
  'id' : OrderId,
  'razorpayPaymentId' : [] | [string],
  'customerName' : string,
  'deliveryTimestamp' : [] | [Timestamp],
  'paymentStatus' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'customerPhone' : string,
  'orderStatus' : OrderStatus,
  'cashbackTimestamp' : [] | [Timestamp],
  'createdAt' : Timestamp,
  'productColor' : string,
  'productId' : ProductId,
  'productName' : string,
  'productSize' : string,
  'customerAddress' : string,
  'razorpayOrderId' : [] | [string],
  'quantity' : bigint,
  'customerEmail' : [] | [string],
  'cashbackStatus' : CashbackStatus,
  'productPrice' : bigint,
}
export type OrderId = bigint;
export interface OrderInput {
  'customerName' : string,
  'paymentMethod' : PaymentMethod,
  'customerPhone' : string,
  'productColor' : string,
  'productId' : ProductId,
  'productName' : string,
  'productSize' : string,
  'customerAddress' : string,
  'razorpayOrderId' : [] | [string],
  'quantity' : bigint,
  'customerEmail' : [] | [string],
  'productPrice' : bigint,
}
export type OrderStatus = { 'shipped' : null } |
  { 'placed' : null } |
  { 'delivered' : null } |
  { 'processing' : null };
export type PaymentMethod = { 'COD' : null } |
  { 'UPI' : null };
export type PaymentStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export interface Product {
  'id' : ProductId,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'commission' : bigint,
  'sizes' : Array<string>,
  'imageUrl' : string,
  'category' : string,
  'colors' : Array<string>,
  'price' : bigint,
}
export type ProductId = bigint;
export interface ProductInput {
  'name' : string,
  'description' : string,
  'commission' : bigint,
  'sizes' : Array<string>,
  'imageUrl' : string,
  'category' : string,
  'colors' : Array<string>,
  'price' : bigint,
}
export type SessionToken = string;
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<[ProductInput], Product>,
  'adminLogin' : ActorMethod<[string, string], LoginResult>,
  'adminLogout' : ActorMethod<[string], undefined>,
  'createOrder' : ActorMethod<[OrderInput], bigint>,
  'createRazorpayOrder' : ActorMethod<[bigint, bigint], string>,
  'deleteProduct' : ActorMethod<[bigint], boolean>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getTotalOrders' : ActorMethod<[], bigint>,
  'getTotalProducts' : ActorMethod<[], bigint>,
  'listOrders' : ActorMethod<[], Array<Order>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'markCashbackGiven' : ActorMethod<[bigint], [] | [Order]>,
  'markDelivered' : ActorMethod<[bigint], [] | [Order]>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateOrderPaymentStatus' : ActorMethod<
    [bigint, PaymentStatus, [] | [string]],
    [] | [Order]
  >,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], [] | [Order]>,
  'updateProduct' : ActorMethod<[bigint, ProductInput], [] | [Product]>,
  'validateAdminSession' : ActorMethod<[string], boolean>,
  'verifyRazorpayPayment' : ActorMethod<[string, string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];