/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ProductInput {
    name: string;
    description: string;
    commission: bigint;
    sizes: Array<string>;
    imageUrl: string;
    category: string;
    colors: Array<string>;
    price: bigint;
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface OrderInput {
    customerName: string;
    paymentMethod: PaymentMethod;
    customerPhone: string;
    productColor: string;
    productId: ProductId;
    productName: string;
    productSize: string;
    customerAddress: string;
    razorpayOrderId?: string;
    quantity: bigint;
    customerEmail?: string;
    productPrice: bigint;
}
export interface Order {
    id: OrderId;
    razorpayPaymentId?: string;
    customerName: string;
    deliveryTimestamp?: Timestamp;
    paymentStatus: PaymentStatus;
    paymentMethod: PaymentMethod;
    customerPhone: string;
    orderStatus: OrderStatus;
    cashbackTimestamp?: Timestamp;
    createdAt: Timestamp;
    productColor: string;
    productId: ProductId;
    productName: string;
    productSize: string;
    customerAddress: string;
    razorpayOrderId?: string;
    quantity: bigint;
    customerEmail?: string;
    cashbackStatus: CashbackStatus;
    productPrice: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type SessionToken = string;
export type ProductId = bigint;
export type LoginResult = {
    __kind__: "ok";
    ok: SessionToken;
} | {
    __kind__: "err";
    err: string;
};
export interface Product {
    id: ProductId;
    name: string;
    createdAt: Timestamp;
    description: string;
    commission: bigint;
    sizes: Array<string>;
    imageUrl: string;
    category: string;
    colors: Array<string>;
    price: bigint;
}
export type OrderId = bigint;
export enum CashbackStatus {
    pending = "pending",
    given = "given"
}
export enum OrderStatus {
    shipped = "shipped",
    placed = "placed",
    delivered = "delivered",
    processing = "processing"
}
export enum PaymentMethod {
    COD = "COD",
    UPI = "UPI"
}
export enum PaymentStatus {
    pending = "pending",
    completed = "completed",
    failed = "failed"
}
export interface backendInterface {
    addProduct(input: ProductInput): Promise<Product>;
    adminLogin(username: string, password: string): Promise<LoginResult>;
    adminLogout(token: string): Promise<void>;
    createOrder(input: OrderInput): Promise<bigint>;
    createRazorpayOrder(amount: bigint, orderId: bigint): Promise<string>;
    deleteProduct(id: bigint): Promise<boolean>;
    getOrder(orderId: bigint): Promise<Order | null>;
    getProduct(id: bigint): Promise<Product | null>;
    getTotalOrders(): Promise<bigint>;
    getTotalProducts(): Promise<bigint>;
    listOrders(): Promise<Array<Order>>;
    listProducts(): Promise<Array<Product>>;
    markCashbackGiven(orderId: bigint): Promise<Order | null>;
    markDelivered(orderId: bigint): Promise<Order | null>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateOrderPaymentStatus(orderId: bigint, status: PaymentStatus, razorpayPaymentId: string | null): Promise<Order | null>;
    updateOrderStatus(orderId: bigint, status: OrderStatus): Promise<Order | null>;
    updateProduct(id: bigint, input: ProductInput): Promise<Product | null>;
    validateAdminSession(token: string): Promise<boolean>;
    verifyRazorpayPayment(razorpayOrderId: string, razorpayPaymentId: string, razorpaySignature: string): Promise<boolean>;
}
import type { CashbackStatus as _CashbackStatus, LoginResult as _LoginResult, Order as _Order, OrderId as _OrderId, OrderInput as _OrderInput, OrderStatus as _OrderStatus, PaymentMethod as _PaymentMethod, PaymentStatus as _PaymentStatus, Product as _Product, ProductId as _ProductId, SessionToken as _SessionToken, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addProduct(arg0: ProductInput): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0);
            return result;
        }
    }
    async adminLogin(arg0: string, arg1: string): Promise<LoginResult> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return from_candid_LoginResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return from_candid_LoginResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminLogout(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogout(arg0);
            return result;
        }
    }
    async createOrder(arg0: OrderInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(to_candid_OrderInput_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(to_candid_OrderInput_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createRazorpayOrder(arg0: bigint, arg1: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createRazorpayOrder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRazorpayOrder(arg0, arg1);
            return result;
        }
    }
    async deleteProduct(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getOrder(arg0: bigint): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: bigint): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalOrders(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalOrders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalOrders();
            return result;
        }
    }
    async getTotalProducts(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalProducts();
            return result;
        }
    }
    async listOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOrders();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOrders();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts();
            return result;
        }
    }
    async markCashbackGiven(arg0: bigint): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.markCashbackGiven(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markCashbackGiven(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async markDelivered(arg0: bigint): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.markDelivered(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markDelivered(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateOrderPaymentStatus(arg0: bigint, arg1: PaymentStatus, arg2: string | null): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderPaymentStatus(arg0, to_candid_PaymentStatus_n22(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg2));
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderPaymentStatus(arg0, to_candid_PaymentStatus_n22(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg2));
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOrderStatus(arg0: bigint, arg1: OrderStatus): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n25(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n25(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProduct(arg0: bigint, arg1: ProductInput): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async validateAdminSession(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateAdminSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateAdminSession(arg0);
            return result;
        }
    }
    async verifyRazorpayPayment(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyRazorpayPayment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyRazorpayPayment(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_CashbackStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CashbackStatus): CashbackStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_LoginResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoginResult): LoginResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    razorpayPaymentId: [] | [string];
    customerName: string;
    deliveryTimestamp: [] | [_Timestamp];
    paymentStatus: _PaymentStatus;
    paymentMethod: _PaymentMethod;
    customerPhone: string;
    orderStatus: _OrderStatus;
    cashbackTimestamp: [] | [_Timestamp];
    createdAt: _Timestamp;
    productColor: string;
    productId: _ProductId;
    productName: string;
    productSize: string;
    customerAddress: string;
    razorpayOrderId: [] | [string];
    quantity: bigint;
    customerEmail: [] | [string];
    cashbackStatus: _CashbackStatus;
    productPrice: bigint;
}): {
    id: OrderId;
    razorpayPaymentId?: string;
    customerName: string;
    deliveryTimestamp?: Timestamp;
    paymentStatus: PaymentStatus;
    paymentMethod: PaymentMethod;
    customerPhone: string;
    orderStatus: OrderStatus;
    cashbackTimestamp?: Timestamp;
    createdAt: Timestamp;
    productColor: string;
    productId: ProductId;
    productName: string;
    productSize: string;
    customerAddress: string;
    razorpayOrderId?: string;
    quantity: bigint;
    customerEmail?: string;
    cashbackStatus: CashbackStatus;
    productPrice: bigint;
} {
    return {
        id: value.id,
        razorpayPaymentId: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.razorpayPaymentId)),
        customerName: value.customerName,
        deliveryTimestamp: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.deliveryTimestamp)),
        paymentStatus: from_candid_PaymentStatus_n12(_uploadFile, _downloadFile, value.paymentStatus),
        paymentMethod: from_candid_PaymentMethod_n14(_uploadFile, _downloadFile, value.paymentMethod),
        customerPhone: value.customerPhone,
        orderStatus: from_candid_OrderStatus_n16(_uploadFile, _downloadFile, value.orderStatus),
        cashbackTimestamp: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.cashbackTimestamp)),
        createdAt: value.createdAt,
        productColor: value.productColor,
        productId: value.productId,
        productName: value.productName,
        productSize: value.productSize,
        customerAddress: value.customerAddress,
        razorpayOrderId: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.razorpayOrderId)),
        quantity: value.quantity,
        customerEmail: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.customerEmail)),
        cashbackStatus: from_candid_CashbackStatus_n18(_uploadFile, _downloadFile, value.cashbackStatus),
        productPrice: value.productPrice
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "completed" in value ? PaymentStatus.completed : "failed" in value ? PaymentStatus.failed : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    COD: null;
} | {
    UPI: null;
}): PaymentMethod {
    return "COD" in value ? PaymentMethod.COD : "UPI" in value ? PaymentMethod.UPI : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipped: null;
} | {
    placed: null;
} | {
    delivered: null;
} | {
    processing: null;
}): OrderStatus {
    return "shipped" in value ? OrderStatus.shipped : "placed" in value ? OrderStatus.placed : "delivered" in value ? OrderStatus.delivered : "processing" in value ? OrderStatus.processing : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    given: null;
}): CashbackStatus {
    return "pending" in value ? CashbackStatus.pending : "given" in value ? CashbackStatus.given : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _SessionToken;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: SessionToken;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n8(_uploadFile, _downloadFile, x));
}
function to_candid_OrderInput_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderInput): _OrderInput {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    paymentMethod: PaymentMethod;
    customerPhone: string;
    productColor: string;
    productId: ProductId;
    productName: string;
    productSize: string;
    customerAddress: string;
    razorpayOrderId?: string;
    quantity: bigint;
    customerEmail?: string;
    productPrice: bigint;
}): {
    customerName: string;
    paymentMethod: _PaymentMethod;
    customerPhone: string;
    productColor: string;
    productId: _ProductId;
    productName: string;
    productSize: string;
    customerAddress: string;
    razorpayOrderId: [] | [string];
    quantity: bigint;
    customerEmail: [] | [string];
    productPrice: bigint;
} {
    return {
        customerName: value.customerName,
        paymentMethod: to_candid_PaymentMethod_n5(_uploadFile, _downloadFile, value.paymentMethod),
        customerPhone: value.customerPhone,
        productColor: value.productColor,
        productId: value.productId,
        productName: value.productName,
        productSize: value.productSize,
        customerAddress: value.customerAddress,
        razorpayOrderId: value.razorpayOrderId ? candid_some(value.razorpayOrderId) : candid_none(),
        quantity: value.quantity,
        customerEmail: value.customerEmail ? candid_some(value.customerEmail) : candid_none(),
        productPrice: value.productPrice
    };
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
} {
    return value == PaymentStatus.pending ? {
        pending: null
    } : value == PaymentStatus.completed ? {
        completed: null
    } : value == PaymentStatus.failed ? {
        failed: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    shipped: null;
} | {
    placed: null;
} | {
    delivered: null;
} | {
    processing: null;
} {
    return value == OrderStatus.shipped ? {
        shipped: null
    } : value == OrderStatus.placed ? {
        placed: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.processing ? {
        processing: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    COD: null;
} | {
    UPI: null;
} {
    return value == PaymentMethod.COD ? {
        COD: null
    } : value == PaymentMethod.UPI ? {
        UPI: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
